spring:
  application:
    name: notify-service
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: docker
kafka:
  bootstrap-servers: kafka:9092

